// Icon stroke colors vary slightly per tier in the original markup
// (free = dim, starter/growth = brighter white, pro = blue-tinted).
const ICONS = {
  free: { stroke: 'rgba(255,255,255,0.35)', check: 'rgba(255,255,255,0.55)' },
  starter: { stroke: 'rgba(255,255,255,0.4)', check: 'rgba(255,255,255,0.7)' },
  growth: { stroke: 'rgba(255,255,255,0.5)', check: '#fff' },
  pro: { stroke: 'rgba(200,230,255,0.5)', check: 'rgba(200,230,255,0.95)' },
};

export const PLANS = [
  {
    id: 'free',
    className: 'pc-free pc-tab-active',
    badge: null,
    name: 'Free',
    nameStyle: null,
    price: '0',
    per: 'forever',
    icons: ICONS.free,
    benefits: [
      '1 listing / day',
      '5 listings / mo cap',
      '30% platform fee',
      'Community support',
      'Basic public profile',
    ],
    btnLabel: 'Get started free',
    btnClassName: 'pc-btn',
  },
  {
    id: 'starter',
    className: 'pc-starter',
    badge: null,
    name: 'Starter',
    nameStyle: null,
    price: '20',
    per: 'per month',
    icons: ICONS.starter,
    benefits: [
      { strong: '5 listings', rest: ' / day' },
      '150 listings / mo',
      { strong: '15% fee', rest: ' — save 15%' },
      'Priority search rank',
      'Email support (24h)',
      'Listing analytics',
      'Seller profile badge',
    ],
    btnLabel: 'Upgrade to Starter',
    btnClassName: 'pc-btn',
  },
  {
    id: 'growth',
    className: 'pc-growth pc-featured',
    badge: { text: 'Most popular', className: 'pc-badge pc-badge-pop' },
    name: 'Growth',
    nameStyle: null,
    price: '40',
    per: 'per month',
    icons: ICONS.growth,
    benefits: [
      { strong: '15 listings', rest: ' / day' },
      'Unlimited / mo',
      { strong: '10% fee', rest: ' — save 20%' },
      'Featured highlights',
      'Priority support (4h)',
      'Advanced analytics',
      'Bulk listing tools',
      'Monthly seller insights',
      'Marketplace email promos',
    ],
    btnLabel: 'Upgrade to Growth',
    btnClassName: 'pc-btn pc-btn-primary',
  },
  {
    id: 'pro',
    className: 'pc-pro',
    badge: { text: 'Best value', className: 'pc-badge' },
    name: 'Pro',
    nameStyle: { color: 'rgba(180,220,255,0.55)' },
    price: '50',
    per: 'per month',
    icons: ICONS.pro,
    benefits: [
      { strong: 'Unlimited', rest: ' daily listings' },
      'Unlimited / mo',
      { strong: '5% only', rest: ' — lowest fee' },
      'Top search placement',
      'DB + hosting for buyers',
      'Admin dash for buyers',
      'Dedicated account mgr',
      'Custom seller storefront',
      'Live chat 24/7',
      'Early feature access',
      'White-glove onboarding',
    ],
    btnLabel: 'Upgrade to Pro',
    btnClassName: 'pc-btn pc-btn-primary',
  },
];
